spring.application.name=SpringAiAndAlibaba

spring.ai.openai.api-key=sk-e5zWuv9LGJfOAiwJMqREqqRli8AJ8hc8eU69AW3MxY5sC2cN
spring.ai.openai.base-url=https://api.xty.app
server.port=8082
# Embedding ?????OpenAI ?????
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.options.dimensions=1536

# Redis ???????? Redis ???
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.ai.vectorstore.redis.index=default-index
spring.ai.vectorstore.redis.prefix=default:
spring.ai.vectorstore.redis.initialize-schema=true