hutool.mail.host=smtp.qq.com

hutool.mail.port=465
hutool.mail.from=766045749@qq.com
hutool.mail.user=766045749@qq.com
hutool.mail.pass=rdezwyfvvynnbddi
hutool.mail.starttls-enable=false
hutool.mail.debug=true
hutool.mail.ssl-enable=true